# Generated by Django 2.2.10 on 2020-05-05 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='fullname',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
