# Generated by Django 2.2.11 on 2020-04-12 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20200410_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='labeling',
            name='end_date',
            field=models.DateTimeField(),
        ),
    ]
