# Generated by Django 2.2.10 on 2020-05-08 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20200505_1158'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='due_date',
            new_name='end_date',
        ),
        migrations.AddField(
            model_name='request',
            name='count_dataset',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='request',
            name='dataset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='backend.Dataset'),
        ),
        migrations.AddField(
            model_name='request',
            name='oneline_description',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='backend.Request')),
            ],
        ),
        migrations.CreateModel(
            name='DatasetDependency',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('mongo_key', models.CharField(max_length=100)),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='backend.Request')),
            ],
        ),
    ]
