# Generated by Django 2.2.11 on 2020-05-09 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20200508_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='thumbnail',
            field=models.TextField(blank=True),
        ),
    ]
