# Generated by Django 2.2.10 on 2020-05-12 09:50

import backend.validation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_request_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='end_date',
            field=models.DateTimeField(validators=[backend.validation.validate_date]),
        ),
    ]
