# Generated by Django 2.2.11 on 2020-04-14 20:16

import backend.validation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20200415_0429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentlog',
            name='type',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=30, validators=[backend.validation.validate_email]),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=30, validators=[backend.validation.validate_phone]),
        ),
        migrations.AlterField(
            model_name='user',
            name='point',
            field=models.IntegerField(default=0),
        ),
    ]
