# Generated by Django 2.2.11 on 2020-04-18 06:47

import backend.validation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20200415_0516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.CharField(max_length=15, validators=[backend.validation.validate_category_type]),
        ),
    ]
