# Generated by Django 2.2.9 on 2020-05-26 22:20

import backend.validation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20200512_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='keywords',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='start_date',
            field=models.DateTimeField(validators=[backend.validation.validate_date]),
        ),
    ]
