# Generated by Django 2.2.10 on 2020-05-28 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_dataset_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentlog',
            name='log_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
