# Generated by Django 2.2.11 on 2020-04-18 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20200418_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_robot',
            field=models.BooleanField(default=False),
        ),
    ]
