# Generated by Django 2.2.10 on 2020-05-29 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_request_is_rewarded'),
    ]

    operations = [
        migrations.AddField(
            model_name='labeling',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
