# Generated by Django 2.2.10 on 2020-05-29 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_labeling_is_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentlog',
            name='amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='paymentlog',
            name='balance',
            field=models.IntegerField(null=True),
        ),
    ]
