# Generated by Django 2.2.11 on 2020-04-23 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_auto_20200420_0252'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='state',
            field=models.CharField(choices=[('RED', 'before_permission'), ('RUN', 'running'), ('END', 'end')], default='RED', max_length=3),
        ),
    ]
