# Generated by Django 2.2.10 on 2020-06-06 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_auto_20200607_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='state',
            field=models.CharField(choices=[('RED', 'before_permission'), ('RUN', 'running'), ('END', 'end'), ('VER', 'verify'), ('VED', 'verified'), ('REW', 'done reword')], default='RED', max_length=3),
        ),
    ]
