# Generated by Django 2.2.11 on 2020-04-10 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='paymentlog',
            name='type',
            field=models.IntegerField(),
        ),
    ]
