# Generated by Django 2.2.11 on 2020-04-14 19:29

import backend.validation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20200412_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=30, validators=[backend.validation.validate_email]),
        ),
        migrations.AlterField(
            model_name='user',
            name='point',
            field=models.IntegerField(default=0, validators=[backend.validation.validate_phone]),
        ),
    ]
