# Generated by Django 2.2.11 on 2020-04-18 11:23

import backend.validation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20200418_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='due_date',
            field=models.DateTimeField(validators=[backend.validation.validate_date], verbose_name='due date'),
        ),
        migrations.AlterField(
            model_name='request',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True, validators=[backend.validation.validate_date]),
        ),
    ]
