# Generated by Django 2.2.11 on 2020-04-19 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_auto_20200419_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='is_captcha',
            field=models.IntegerField(default=0),
        ),
    ]
